### ISSUE TITLE
Process Crashing

### ISSUE THREAD

**Issue by amonaco** [simonmacmullen/rabbitmq-auth-backend-http#10]
Hi Simon,

I'm trying to set up the module on 3.4.4. I've built and configured without issues but I'm getting the following error upon connection:

```
=ERROR REPORT==== 6-Mar-2015::17:47:16 ===
** Generic server <0.518.0> terminating
** Last message in was connect
** When Server state == {<0.517.0>,
                         {amqp_params_direct,<<"guest">>,<<"guest">>,<<"/">>,
                             rabbit@e4,
                             {amqp_adapter_info,
                                 {0,0,0,0,0,0,0,1},
                                 1883,
                                 {0,0,0,0,0,0,0,1},
                                 51104,<<"[::1]:51104 -> [::1]:1883">>,
                                 {'MQTT',"3.1.0"},
                                 [{ssl,false}]},
                             []}}
** Reason for termination ==
** {function_clause,
       [{amqp_gen_connection,terminate,
            [{{case_clause,
                  {badrpc,
                      {'EXIT',
                          {undef,
                              [{rabbit_auth_backend_http,check_user_login,
                                   [<<"guest">>,[{password,<<"guest">>}]],
                                   []},
                               {rabbit_access_control,try_login,3,
                                   [{file,"src/rabbit_access_control.erl"},
                                    {line,82}]},
                               {lists,foldl,3,
                                   [{file,"lists.erl"},{line,1197}]},
                               {rabbit_access_control,check_user_login,2,
                                   [{file,"src/rabbit_access_control.erl"},
                                    {line,57}]},
                               {rabbit_direct,connect0,5,
                                   [{file,"src/rabbit_direct.erl"},{line,85}]},
                               {rpc,local_call,3,
                                   [{file,"rpc.erl"},{line,327}]},
                               {amqp_direct_connection,connect,4,
                                   [{file,"src/amqp_direct_connection.erl"},
                                    {line,133}]},
                               {amqp_gen_connection,handle_call,3,
                                   [{file,"src/amqp_gen_connection.erl"},
                                    {line,171}]}]}}}},
              [{amqp_direct_connection,connect,4,
                   [{file,"src/amqp_direct_connection.erl"},{line,133}]},
               {amqp_gen_connection,handle_call,3,
                   [{file,"src/amqp_gen_connection.erl"},{line,171}]},
               {gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,588}]},
               {proc_lib,init_p_do_apply,3,
                   [{file,"proc_lib.erl"},{line,227}]}]},
             {<0.517.0>,
              {amqp_params_direct,<<"guest">>,<<"guest">>,<<"/">>,rabbit@e4,
                  {amqp_adapter_info,
                      {0,0,0,0,0,0,0,1},
                      1883,
                      {0,0,0,0,0,0,0,1},
                      51104,<<"[::1]:51104 -> [::1]:1883">>,
                      {'MQTT',"3.1.0"},
                      [{ssl,false}]},
                  []}}],
            [{file,"src/amqp_gen_connection.erl"},{line,230}]},
        {gen_server,terminate,6,[{file,"gen_server.erl"},{line,722}]},
        {proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,227}]}]}
```
I think this means that the Erlang process is terminating. Application stays up and running. Any suggestions much appreciated.

Thanks

**Comment by simonmacmullen** [comment]
It looks like you have built the plugin from git master against git master RabbitMQ, but are trying to run it against 3.4.4? That won't work, the APIs the plugin hooks into have changed.

You might want to download a ready made version from http://www.rabbitmq.com/community-plugins/v3.4.x/ instead.

**Comment by amonaco** [comment]
Thanks for your reply but binaries plugins are not an option. Our company back-end replies JSON and I need to add that format to your plugin. Therefore, I need to be able to code and build. There might be a lot of people in a similar situation...

**Comment by simonmacmullen** [comment]
In that case, either build master and run it against 3.5.0, or checkout rabbitmq_v3_4_4 for the public umbrella and server etc, and revision 76c3a3c2969d4f2e147bc5e51812dfe70a578908 for this repo. That will get you a 3.4.x-compatible plugin.

**Comment by simonmacmullen** [comment]
Oh, and a pull request to support JSON would be awesome :-)

**Comment by amonaco** [comment]
Thanks for the tip. I'll work on it and send you a pull request when done ;)

**Comment by VinayNadig** [comment]
Have tested with RMQ 3.2.4-1(Default version on Ubuntu 14.04) and can confirm that it does not work. 

Plugin works fine with RMQ 3.5.3 (Downloaded deb from RMQ site.)

**Comment by arashbina** [comment]
I'm using version 3.5.x-fe9401c6 of the plugin with RabbitMQ 3.5.4 and it doesn't seem to work.

This is what I get:

ERROR REPORT==== 6-Oct-2015::19:33:49 ===
** Generic server <0.376.0> terminating
** Last message in was {inet_async,#Port<0.8426>,166,
{ok,<<16,36,0,4,77,81,84,84,4,194,0,60,0,6,103,
						117,101,115,116,49,0,6,117,115,101,114,48,
						49,0,8,97,115,100,102,118,49,50,51>>}}
** When Server state == {state,#Port<0.8426>,
"10.0.2.2:49177 -> 172.17.0.189:1883",true,
						running,
						{none,none},
						<0.377.0>,false,none,
						{proc_state,#Port<0.8426>,
						{dict,0,16,16,8,80,48,
						{[],[],[],[],[],[],[],[],[],[],[],[],[],
						[],[],[]},
						{{[],[],[],[],[],[],[],[],[],[],[],[],[],
						[],[],[]}}},
						{undefined,undefined},
						{0,nil},
						{0,nil},
						undefined,1,undefined,undefined,undefined,
						{undefined,undefined},
						undefined,<<"amq.topic">>,none}}
** Reason for termination ==
** {{function_clause,
[{amqp_gen_connection,terminate,
			[{{case_clause,
				{badrpc,
					{'EXIT',
						{undef,
						[{rabbitmq_auth_backend_http,
						user_login_authentication,
						[<<"user01">>,[{password,<<"xxx">>}]],
						[]},
						{rabbit_access_control,try_authenticate,3,[]},
						{rabbit_access_control,
						'-check_user_login/2-fun-0-',4,[]},
						{lists,foldl,3,
						[{file,"lists.erl"},{line,1261}]},
						{rabbit_direct,connect0,5,[]},
						{rpc,local_call,3,
						[{file,"rpc.erl"},{line,329}]},
						{amqp_direct_connection,connect,4,[]},
						{amqp_gen_connection,handle_call,3,[]}]}}}},
			[{amqp_direct_connection,connect,4,[]},
			{amqp_gen_connection,handle_call,3,[]},
			{gen_server,try_handle_call,4,
				[{file,"gen_server.erl"},{line,607}]},
			{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,639}]},
			{proc_lib,init_p_do_apply,3,
				[{file,"proc_lib.erl"},{line,237}]}]},
			{<0.379.0>,
			{amqp_params_direct,<<"user01">>,<<"xxx">>,<<"/">>,
				rabbit@0eb5e78164c8,
				{amqp_adapter_info,
					{0,0,0,0,0,65535,44049,189},
					1883,
					{0,0,0,0,0,65535,2560,514},
					49177,<<"10.0.2.2:49177 -> 172.17.0.189:1883">>,
					{'MQTT',"3.1.1"},
					[{ssl,false}]},
				[]}}],
			[]},
		{gen_server,try_terminate,3,[{file,"gen_server.erl"},{line,621}]},
		{gen_server,terminate,7,[{file,"gen_server.erl"},{line,787}]},
		{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,237}]}]},
{gen_server,call,[<0.380.0>,connect,infinity]}}

**Comment by michaelklishin** [comment]
`undef` means a function doesn't exist, so this can be a compatibility issue. We will take a look after releasing `3.5.6`, thanks.
